- hosts: localhost
  gather_facts: no
  roles:
    - composer
  vars:
    config_files: []
    config_data: []
    WP_BINARY: utilities/wp-cli/bin/wp
    WP_GROUP: apache
    MYSQLDBPASS: "{{ MYSQLDBPASS }}"
    FOLDERNAME: "{{ FOLDERNAME }}"
    ADMIN_EMAIL: "{{ ADMIN_EMAIL }}"

  tasks:
    - import_tasks: tasks/wp-cli.yml
    - import_tasks: tasks/google-drive-upload.yml
    - import_tasks: tasks/wordpress_update.yml
