---
- set_fact:
    skip_themes: False
    skip_plugins: False

- name: determine if this is a wordpress vhost
  stat:
    path: "{{ bu.stdout|trim }}/wp-config.php"
  register: wpsite

- name: borrow some vars
  shell: |
    grep -e '^define.*{{ item }}' {{ bu.stdout|trim }}/wp-config.php | cut -d "'" -f 4
  register: WPCONFIG
  become: yes
  loop:
    - DB_NAME
    - DB_USER
    - DB_PASSWORD
    - DB_HOST
  when: wpsite.stat.exists

- name: find problem plugins
  stat:
    path: "{{ bu.stdout|trim }}/wp-content/plugins/{{ item }}"
  loop: "{{ SkipPlugins }}"
  register: badplugin
  when: wpsite.stat.exists

- set_fact:
    skip_plugins: True
  when: wpsite.stat.exists is defined and item.stat.isdir is defined 
  loop: "{{ badplugin.results }}"

- name: find problem themes
  stat:
    path: "{{ bu.stdout|trim }}/wp-content/themes/{{ item }}"
  loop: "{{ SkipThemes }}"
  register: badtheme
  when: wpsite.stat.exists

- set_fact:
    skip_themes: True
  when: wpsite.stat.exists is defined and item.stat.isdir is defined 
  loop: "{{ badtheme.results }}"

- include: tasks/update_host_backup.yml
  when: wpsite.stat.exists and BACKUPALL is defined

- include: tasks/update_host_plugins.yml
  when: wpsite.stat.exists  and UPDATEPLUGINS is defined

# really, consider only manually updating themes.  or, only updating non-active themes
- include: tasks/update_host_themes.yml
  when: wpsite.stat.exists and UPDATETHEMES is defined

- include: tasks/update_host_core.yml
  when: wpsite.stat.exists and UPDATECORE is defined

- debug: msg="stats {{ wpsite.stat.exists }} core {{ UPDATECORE | default('no update') }}"
