- name: list of config files
  shell: grep DocumentRoot {{ DocumentRoot }} | grep public_html | cut -d ':' -f 1 | grep -v le-ssl.conf
  register: apache_conf

- name: apache_conf
  debug: msg={{ apache_conf.stdout_lines }}

# check core, if check fails e-mail someone.
# if we can update core, check plugins. rinse repeat. themes. rinse repeat.
# add a check to see if there's wp-config.php in the users home directory before doing all the wp stuff
- name: do all the things
  raw: |
    DATE=`date +"%Y-%m-%d"`
    WP_GROUP={{ WP_GROUP }}
    PLAYBOOK_DIR={{ playbook_dir }}
    WP_SITE=$(grep -oP '(ServerName.*|DocumentRoot.*)' {{ item }} | sed ':a;N;$!ba;s/\n/ /g' | cut -d ' ' -f 2)
    WP_USER=$(grep -oP '(ServerName.*|DocumentRoot.*)' {{ item }} | sed ':a;N;$!ba;s/\n/ /g' | cut -d ' ' -f 4 | cut -d '/' -f 3)
    WP_PATH=$(grep -oP '(ServerName.*|DocumentRoot.*)' {{ item }} | sed ':a;N;$!ba;s/\n/ /g' | cut -d ' ' -f 4)
    if [ ! -f "$WP_PATH/wp-config.php" ]; then exit; fi
    WP_USER_HOME="/home/$WP_USER"
    WP_DB=$(grep DB_NAME $WP_PATH/wp-config.php | cut -d ',' -f 2 | grep -Po "(?<=')[^']*" | head -n 1); 
    # create backup of database and content files
    if [ ! -z "$WP_USER" ] && [ -f "$WP_PATH/wp-config.php" ] && [ ! -f "$WP_USER_HOME/$DATE-$WP_SITE.sql" ]; then mysqldump -p{{ MYSQLDBPASS}} $WP_DB > $WP_USER_HOME/$DATE-$WP_SITE.sql; fi
    if [ ! -z "$WP_USER" ] && [ -f "$WP_PATH/wp-config.php" ] && [ ! -f "$WP_USER_HOME/$DATE-$WP_SITE.tar.gz" ]; then tar czvf $WP_USER_HOME/$DATE-$WP_SITE.tar.gz $WP_PATH $WP_USER_HOME/$DATE-$WP_SITE.sql; fi
    # push to google drive
    if [ ! -z "$WP_USER" ] && [ -f "$WP_PATH/wp-config.php" ] && [ -f "$WP_USER_HOME/$DATE-$WP_SITE.tar.gz" ]; then cd $PLAYBOOK_DIR/utilities/google-drive-upload; ./upload.sh $WP_USER_HOME/$DATE-$WP_SITE.tar.gz {{ FOLDERNAME }}; fi
    # remove db and tar file
    if [ ! -z "$WP_USER" ] && [ -f "$WP_PATH/wp-config.php" ] && [ -f "$WP_USER_HOME/$DATE-$WP_SITE.sql" ]; then rm $WP_USER_HOME/$DATE-$WP_SITE.sql; fi
    if [ ! -z "$WP_USER" ] && [ -f "$WP_PATH/wp-config.php" ] && [ -f "$WP_USER_HOME/$DATE-$WP_SITE.tar.gz" ]; then rm $WP_USER_HOME/$DATE-$WP_SITE.tar.gz; fi
  with_items: "{{ apache_conf.stdout_lines }}"
  ignore_errors: true
