- name: list of config files
  shell: grep DocumentRoot {{ DocumentRoot }} | grep public_html | cut -d ':' -f 1 | grep -v le-ssl.conf
  register: apache_conf

- name: find user and home directory
  raw: |
    grep DocumentRoot {{ item }} | sed -e 's/^[[:space:]]*DocumentRoot[[:space:]]//' -e 's/[[:space:]]*$//'
  loop: "{{ apache_conf.stdout_lines }}"
  register: findvhost

- name: create wp cache dir
  file:
    path: "{{ item.stdout.split('public_html')[0] }}.wp-cli/cache"
    state: directory
    recurse: yes
    mode: '0755'
    owner: "{{ item.stdout.split('/')[2] }}"
    group: "{{ item.stdout.split('/')[2] }}"
  loop: "{{ findvhost.results }}"
  become: yes
  when: canceledfornow is defined

# go for a loop, IF we have a wp-config.php

- include: tasks/update_host.yml
  loop: "{{ findvhost.results }}"
  loop_control:
    loop_var: bu
  become: yes
